use_frameworks!

platform :ios, '9.0'

target 'Rudder-Leanplum_Example' do
  pod 'Rudder-Leanplum', :path => '../'

  target 'Rudder-Leanplum_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
